export const DEFAULT_SETTINGS = {
  dailyTargetMinutes: 6 * 60,
  focusMinutes: 50,
  shortBreakMinutes: 10,
  longBreakMinutes: 25,
  sessionsBeforeLongBreak: 4,
  soundEnabled: true,
};

export const STATUS_META = [
  {
    id: "notStarted",
    title: "Not started",
    shortTitle: "Red",
    description: "You have not touched this section yet.",
    color: "#ff5d5d",
    soft: "rgba(255, 93, 93, 0.16)",
    progressScore: 0,
  },
  {
    id: "needsReview",
    title: "Needs more review",
    shortTitle: "Rose",
    description: "You covered it once, but it still feels shaky.",
    color: "#ff8b9d",
    soft: "rgba(255, 139, 157, 0.16)",
    progressScore: 0.3,
  },
  {
    id: "inProgress",
    title: "In progress",
    shortTitle: "Amber",
    description: "This section is actively in your current rotation.",
    color: "#ffbf47",
    soft: "rgba(255, 191, 71, 0.16)",
    progressScore: 0.55,
  },
  {
    id: "secondPass",
    title: "Second pass",
    shortTitle: "Blue",
    description: "You are already doing recall and memory work here.",
    color: "#55a6ff",
    soft: "rgba(85, 166, 255, 0.16)",
    progressScore: 0.8,
  },
  {
    id: "examReady",
    title: "Exam ready",
    shortTitle: "Green",
    description: "This section feels solid and ready for bar-level recall.",
    color: "#45d483",
    soft: "rgba(69, 212, 131, 0.16)",
    progressScore: 1,
  },
  {
    id: "onHold",
    title: "On hold",
    shortTitle: "Gray",
    description: "Temporarily parked while other sections get priority.",
    color: "#95a2b8",
    soft: "rgba(149, 162, 184, 0.16)",
    progressScore: 0.12,
  },
];

export const EXAM_SCHEDULE = [
  {
    id: "day1-am",
    label: "Day 1",
    dateLabel: "September 6, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Political and Public International Law",
    weight: "15%",
  },
  {
    id: "day1-pm",
    label: "Day 1",
    dateLabel: "September 6, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Commercial and Taxation Laws",
    weight: "20%",
  },
  {
    id: "day2-am",
    label: "Day 2",
    dateLabel: "September 9, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Civil Law and Land Titles and Deeds",
    weight: "20%",
  },
  {
    id: "day2-pm",
    label: "Day 2",
    dateLabel: "September 9, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Labor and Social Legislation",
    weight: "10%",
  },
  {
    id: "day3-am",
    label: "Day 3",
    dateLabel: "September 13, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Criminal Law",
    weight: "10%",
  },
  {
    id: "day3-pm",
    label: "Day 3",
    dateLabel: "September 13, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Remedial Law, Legal and Judicial Ethics, with Practical Exercises",
    weight: "25%",
  },
];

export const SUBJECTS = [
  {
    id: "political-public-international-law",
    title: "Political and Public International Law",
    weight: "15%",
    examWindow: "Day 1 • Morning",
    examDay: "September 6, 2026",
    bulletinPageRange: [6, 14],
    summary: "Constitutional structure, rights, public officers, election law, local governments, and public international law.",
    sections: [
      { id: "pol-basic-concepts", title: "I. BASIC CONCEPTS" },
      { id: "pol-national-territory", title: "II. NATIONAL TERRITORY" },
      { id: "pol-citizenship", title: "III. CITIZENSHIP" },
      { id: "pol-legislative", title: "IV. LEGISLATIVE DEPARTMENT" },
      { id: "pol-executive", title: "V. EXECUTIVE DEPARTMENT" },
      { id: "pol-judicial", title: "VI. JUDICIAL DEPARTMENT" },
      { id: "pol-constitutional-commissions", title: "VII. CONSTITUTIONAL COMMISSIONS" },
      { id: "pol-constitutional-rights", title: "VIII. CONSTITUTIONAL RIGHTS" },
      { id: "pol-national-economy", title: "IX. NATIONAL ECONOMY AND PATRIMONY" },
      { id: "pol-administrative-law", title: "X. ADMINISTRATIVE LAW" },
      { id: "pol-public-officers", title: "XI. LAW ON PUBLIC OFFICERS" },
      { id: "pol-election-law", title: "XII. ELECTION LAW" },
      { id: "pol-local-governments", title: "XIII. LOCAL GOVERNMENTS" },
      { id: "pol-public-international-law", title: "XIV. PUBLIC INTERNATIONAL LAW" },
    ],
  },
  {
    id: "commercial-taxation-laws",
    title: "Commercial and Taxation Laws",
    weight: "20%",
    examWindow: "Day 1 • Afternoon",
    examDay: "September 6, 2026",
    bulletinPageRange: [15, 24],
    summary: "Corporations, insurance, banking, intellectual property, special commercial statutes, and core tax rules and remedies.",
    sections: [
      { id: "comm-business-organizations", title: "I. BUSINESS ORGANIZATIONS" },
      { id: "comm-insurance", title: "II. INSURANCE" },
      { id: "comm-transportation", title: "III. TRANSPORTATION" },
      { id: "comm-banking", title: "IV. BANKING" },
      { id: "comm-intellectual-property", title: "V. INTELLECTUAL PROPERTY" },
      { id: "comm-special-commercial-laws", title: "VI. SPECIAL COMMERCIAL LAWS" },
      { id: "comm-taxation-law", title: "VIII. TAXATION LAW" },
    ],
  },
  {
    id: "civil-law-land-titles",
    title: "Civil Law and Land Titles and Deeds",
    weight: "20%",
    examWindow: "Day 2 • Morning",
    examDay: "September 9, 2026",
    bulletinPageRange: [25, 33],
    summary: "Civil code foundations, family law, property, land titles, succession, obligations, contracts, quasi-delicts, and damages.",
    sections: [
      { id: "civil-effect-application", title: "I. EFFECT AND APPLICATION OF LAWS" },
      { id: "civil-persons", title: "II. PERSONS" },
      { id: "civil-family-relations", title: "III. FAMILY RELATIONS" },
      { id: "civil-civil-register", title: "IV. CIVIL REGISTER" },
      { id: "civil-property", title: "V. PROPERTY, OWNERSHIP, AND ITS MODIFICATIONS" },
      { id: "civil-land-titles", title: "VI. LAND TITLES AND DEEDS" },
      { id: "civil-succession", title: "VII. SUCCESSION" },
      { id: "civil-obligations-contracts", title: "VIII. OBLIGATIONS AND CONTRACTS" },
      { id: "civil-special-contracts", title: "IX. SPECIAL CONTRACTS" },
      { id: "civil-quasi-contracts", title: "X. QUASI-CONTRACTS" },
      { id: "civil-torts", title: "XI. TORTS AND QUASI-DELICTS" },
      { id: "civil-damages", title: "XII. DAMAGES" },
    ],
  },
  {
    id: "labor-social-legislation",
    title: "Labor and Social Legislation",
    weight: "10%",
    examWindow: "Day 2 • Afternoon",
    examDay: "September 9, 2026",
    bulletinPageRange: [34, 41],
    summary: "Labor policies, recruitment, employment relationship, labor standards, labor relations, termination, social legislation, and remedies.",
    sections: [
      { id: "labor-basic-principles", title: "I. BASIC PRINCIPLES AND CONCEPTS" },
      { id: "labor-recruitment", title: "II. RECRUITMENT AND PLACEMENT" },
      { id: "labor-employment-relationship", title: "III. EMPLOYMENT RELATIONSHIP" },
      { id: "labor-standards", title: "IV. LABOR STANDARDS" },
      { id: "labor-relations", title: "V. LABOR RELATIONS" },
      { id: "labor-suspension-termination", title: "VI. SUSPENSION AND TERMINATION OF EMPLOYMENT" },
      { id: "labor-social-legislation", title: "VII. SOCIAL LEGISLATION" },
      { id: "labor-adjudication", title: "VIII. LABOR ADJUDICATION: JURISDICTION & REMEDIES" },
    ],
  },
  {
    id: "criminal-law",
    title: "Criminal Law",
    weight: "10%",
    examWindow: "Day 3 • Morning",
    examDay: "September 13, 2026",
    bulletinPageRange: [42, 46],
    summary: "Fundamental penal principles, criminal liability, penalties, extinction of liability, and the special laws integrated into Book II crimes.",
    sections: [
      { id: "crim-fundamental-principles", title: "I. FUNDAMENTAL PRINCIPLES" },
      { id: "crim-felonies-liability", title: "II. FELONIES AND CRIMINAL LIABILITY" },
      { id: "crim-crimes-penalties", title: "III. CRIMES AND THEIR PENALTIES" },
    ],
  },
  {
    id: "remedial-ethics-practical",
    title: "Remedial Law, Legal and Judicial Ethics, with Practical Exercises",
    weight: "25%",
    examWindow: "Day 3 • Afternoon",
    examDay: "September 13, 2026",
    bulletinPageRange: [47, 62],
    summary: "Procedure, evidence, writs, remedies, ethics, and bar-style drafting tasks.",
    sections: [
      { id: "rem-general-principles", title: "I. GENERAL PRINCIPLES" },
      { id: "rem-jurisdiction", title: "II. JURISDICTION" },
      { id: "rem-civil-procedure", title: "III. CIVIL PROCEDURE" },
      { id: "rem-provisional-remedies", title: "IV. PROVISIONAL REMEDIES" },
      { id: "rem-special-civil-actions", title: "V. SPECIAL CIVIL ACTIONS" },
      { id: "rem-special-proceedings", title: "VI. SPECIAL PROCEEDINGS AND WRITS" },
      { id: "rem-criminal-procedure", title: "VII. CRIMINAL PROCEDURE" },
      { id: "rem-evidence", title: "VIII. EVIDENCE" },
      { id: "rem-legal-judicial-ethics", title: "IX. LEGAL AND JUDICIAL ETHICS" },
      { id: "rem-practical-exercises", title: "X. PRACTICAL EXERCISES" },
    ],
  },
];

export const TOTAL_SECTIONS = SUBJECTS.reduce((total, subject) => total + subject.sections.length, 0);
