export const DEFAULT_SETTINGS = {
  dailyTargetMinutes: 6 * 60,
  focusMinutes: 50,
  shortBreakMinutes: 10,
  longBreakMinutes: 25,
  sessionsBeforeLongBreak: 4,
};

export const STATUS_META = [
  {
    id: "notStarted",
    title: "Not started",
    shortTitle: "Red",
    description: "You have not touched this section yet.",
    color: "#ff5d5d",
    soft: "rgba(255, 93, 93, 0.16)",
    progressScore: 0,
  },
  {
    id: "needsReview",
    title: "Needs more review",
    shortTitle: "Rose",
    description: "You covered it once, but it still feels shaky.",
    color: "#ff8b9d",
    soft: "rgba(255, 139, 157, 0.16)",
    progressScore: 0.3,
  },
  {
    id: "inProgress",
    title: "In progress",
    shortTitle: "Amber",
    description: "This section is actively in your current rotation.",
    color: "#ffbf47",
    soft: "rgba(255, 191, 71, 0.16)",
    progressScore: 0.55,
  },
  {
    id: "secondPass",
    title: "Second pass",
    shortTitle: "Blue",
    description: "You are already doing recall and memory work here.",
    color: "#55a6ff",
    soft: "rgba(85, 166, 255, 0.16)",
    progressScore: 0.8,
  },
  {
    id: "examReady",
    title: "Exam ready",
    shortTitle: "Green",
    description: "This section feels solid and ready for bar-level recall.",
    color: "#45d483",
    soft: "rgba(69, 212, 131, 0.16)",
    progressScore: 1,
  },
  {
    id: "onHold",
    title: "On hold",
    shortTitle: "Gray",
    description: "Temporarily parked while other sections get priority.",
    color: "#95a2b8",
    soft: "rgba(149, 162, 184, 0.16)",
    progressScore: 0.12,
  },
];

export const EXAM_SCHEDULE = [
  {
    id: "day1-am",
    label: "Day 1",
    dateLabel: "September 6, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Political and Public International Law",
    weight: "15%",
  },
  {
    id: "day1-pm",
    label: "Day 1",
    dateLabel: "September 6, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Commercial and Taxation Laws",
    weight: "20%",
  },
  {
    id: "day2-am",
    label: "Day 2",
    dateLabel: "September 9, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Civil Law and Land Titles and Deeds",
    weight: "20%",
  },
  {
    id: "day2-pm",
    label: "Day 2",
    dateLabel: "September 9, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Labor and Social Legislation",
    weight: "10%",
  },
  {
    id: "day3-am",
    label: "Day 3",
    dateLabel: "September 13, 2026",
    sessionLabel: "8:00 AM - 12:00 PM",
    subject: "Criminal Law",
    weight: "10%",
  },
  {
    id: "day3-pm",
    label: "Day 3",
    dateLabel: "September 13, 2026",
    sessionLabel: "2:00 PM - 6:00 PM",
    subject: "Remedial Law, Legal and Judicial Ethics, with Practical Exercises",
    weight: "25%",
  },
];

export const SUBJECTS = [
  {
    id: "political-public-international-law",
    title: "Political and Public International Law",
    weight: "15%",
    examWindow: "Day 1 • Morning",
    examDay: "September 6, 2026",
    bulletinPageRange: [6, 14],
    summary: "Constitutional structure, rights, public officers, election law, local governments, and public international law.",
    sections: [
      { id: "pol-basic-concepts", title: "Basic Concepts" },
      { id: "pol-national-territory", title: "National Territory" },
      { id: "pol-citizenship", title: "Citizenship" },
      { id: "pol-legislative", title: "Legislative Department" },
      { id: "pol-executive", title: "Executive Department" },
      { id: "pol-judicial", title: "Judicial Department" },
      { id: "pol-constitutional-commissions", title: "Constitutional Commissions" },
      { id: "pol-constitutional-rights", title: "Constitutional Rights" },
      { id: "pol-social-justice", title: "Social Justice and Human Rights" },
      { id: "pol-academic-freedom", title: "Academic Freedom" },
      { id: "pol-national-economy", title: "National Economy and Patrimony" },
      { id: "pol-administrative-law", title: "Administrative Law" },
      { id: "pol-public-officers", title: "Law on Public Officers" },
      { id: "pol-election-law", title: "Election Law" },
      { id: "pol-local-governments", title: "Local Governments" },
      { id: "pol-public-international-law", title: "Public International Law" },
    ],
  },
  {
    id: "commercial-taxation-laws",
    title: "Commercial and Taxation Laws",
    weight: "20%",
    examWindow: "Day 1 • Afternoon",
    examDay: "September 6, 2026",
    bulletinPageRange: [15, 24],
    summary: "Corporations, insurance, banking, intellectual property, special commercial statutes, and core tax rules and remedies.",
    sections: [
      { id: "comm-business-organizations", title: "Business Organizations" },
      { id: "comm-insurance", title: "Insurance" },
      { id: "comm-transportation", title: "Transportation" },
      { id: "comm-banking", title: "Banking" },
      { id: "comm-intellectual-property", title: "Intellectual Property" },
      { id: "comm-special-commercial-laws", title: "Special Commercial Laws" },
      { id: "comm-taxation-law", title: "Taxation Law" },
    ],
  },
  {
    id: "civil-law-land-titles",
    title: "Civil Law and Land Titles and Deeds",
    weight: "20%",
    examWindow: "Day 2 • Morning",
    examDay: "September 9, 2026",
    bulletinPageRange: [25, 33],
    summary: "Civil code foundations, family law, property, land titles, succession, obligations, contracts, quasi-delicts, and damages.",
    sections: [
      { id: "civil-effect-application", title: "Effect and Application of Laws" },
      { id: "civil-persons", title: "Persons" },
      { id: "civil-family-relations", title: "Family Relations" },
      { id: "civil-civil-register", title: "Civil Register" },
      { id: "civil-property", title: "Property, Ownership, and its Modifications" },
      { id: "civil-land-titles", title: "Land Titles and Deeds" },
      { id: "civil-succession", title: "Succession" },
      { id: "civil-obligations-contracts", title: "Obligations and Contracts" },
      { id: "civil-special-contracts", title: "Special Contracts" },
      { id: "civil-quasi-contracts", title: "Quasi-Contracts" },
      { id: "civil-torts", title: "Torts and Quasi-Delicts" },
      { id: "civil-damages", title: "Damages" },
    ],
  },
  {
    id: "labor-social-legislation",
    title: "Labor and Social Legislation",
    weight: "10%",
    examWindow: "Day 2 • Afternoon",
    examDay: "September 9, 2026",
    bulletinPageRange: [34, 41],
    summary: "Labor policies, recruitment, employment relationship, labor standards, labor relations, termination, social legislation, and remedies.",
    sections: [
      { id: "labor-basic-principles", title: "Basic Principles and Concepts" },
      { id: "labor-recruitment", title: "Recruitment and Placement" },
      { id: "labor-employment-relationship", title: "Employment Relationship" },
      { id: "labor-standards", title: "Labor Standards" },
      { id: "labor-relations", title: "Labor Relations" },
      { id: "labor-suspension-termination", title: "Suspension and Termination of Employment" },
      { id: "labor-social-legislation", title: "Social Legislation" },
      { id: "labor-adjudication", title: "Labor Adjudication: Jurisdiction and Remedies" },
    ],
  },
  {
    id: "criminal-law",
    title: "Criminal Law",
    weight: "10%",
    examWindow: "Day 3 • Morning",
    examDay: "September 13, 2026",
    bulletinPageRange: [42, 46],
    summary: "Fundamental penal principles, criminal liability, penalties, extinction of liability, and the special laws integrated into Book II crimes.",
    sections: [
      { id: "crim-fundamental-principles", title: "Fundamental Principles" },
      { id: "crim-felonies-liability", title: "Felonies and Criminal Liability" },
      { id: "crim-crimes-penalties", title: "Crimes and Their Penalties" },
    ],
  },
  {
    id: "remedial-ethics-practical",
    title: "Remedial Law, Legal and Judicial Ethics, with Practical Exercises",
    weight: "25%",
    examWindow: "Day 3 • Afternoon",
    examDay: "September 13, 2026",
    bulletinPageRange: [47, 62],
    summary: "Procedure, evidence, writs, remedies, ethics, and bar-style drafting tasks.",
    sections: [
      { id: "rem-general-principles", title: "General Principles" },
      { id: "rem-jurisdiction", title: "Jurisdiction" },
      { id: "rem-civil-procedure", title: "Civil Procedure" },
      { id: "rem-provisional-remedies", title: "Provisional Remedies" },
      { id: "rem-special-civil-actions", title: "Special Civil Actions" },
      { id: "rem-special-proceedings", title: "Special Proceedings and Writs" },
      { id: "rem-criminal-procedure", title: "Criminal Procedure" },
      { id: "rem-evidence", title: "Evidence" },
      { id: "rem-legal-judicial-ethics", title: "Legal and Judicial Ethics" },
      { id: "rem-practical-exercises", title: "Practical Exercises" },
    ],
  },
];

export const TOTAL_SECTIONS = SUBJECTS.reduce((total, subject) => total + subject.sections.length, 0);
